import { execa } from "execa";
import prompts from "prompts";
import { readFile, writeFile } from "fs/promises";
import { rm } from "fs/promises";
import path from "path";
import process from "process";

async function createNextProject() {
    const data = await prompts([
        {
            type: "text",
            name: "dirName",
            message: "What will be your project's directory name?",
            initial: "my-app",
            validate: m => !m.trim() ? "Value cannot be empty" : true,
        },
        {
            type: "text",
            name: "title",
            message: "What will be your project's HTML title?",
            initial: "My App",
            validate: m => !m.trim() ? "Value cannot be empty" : true,
        },
        {
            type: "text",
            name: "desc",
            message: "What will be your project's HTML description?",
            initial: "App built with Create Next App",
            validate: m => !m.trim() ? "Value cannot be empty" : true,
        }
    ]);

    if(
        !data.dirName ||
        !data.title ||
        !data.desc ||
        !data.includeDevNotes
    ) {
        console.log("> Incomplete Data. Aborting process");
        process.exit(1);
    }

    await execa(
        "bunx",
        [
            "create-next-app@latest",
            data.dirName,
            "--yes",
            "--skip-install"
        ]
    );

    const rootPath = path.resolve(process.cwd(), data.dirName);

    console.log(`> Entering ${rootPath}`);

    await execa("bun", ["install"], {
        cwd: rootPath,
        stdio: "inherit",
    });

    await execa(
        "bun",
        [
            "add",
            "-d", 
            "prettier", 
            "eslint-config-prettier",
            "eslint-plugin-prettier"
        ],
        {
            cwd: rootPath,
            stdio: "inherit",
        }
    );

    await cleanup(rootPath);
    await setDefaults(rootPath);
    await editLayoutMetadata(rootPath, data.title, data.desc);
    await setupFormatting(rootPath);
    await addFormatScript(rootPath);
    await addTypeModule(rootPath);

    await formatAllFiles(rootPath);

    await initializeRepo(rootPath);
}

async function deletePremadeNextFiles(rootPath: string): Promise<void> {
    const publicPath = path.join(rootPath, "public");
    await rm(publicPath, {
        recursive: true,
        force: true,
    });

    const readmePath = path.join(rootPath, "README.md");
    await rm(readmePath, {
        recursive: true,
        force: true,
    });

    const gitPath = path.join(rootPath, ".git");
    await rm(gitPath, {
        recursive: true,
        force: true,
    });
}

async function setupPrettier(rootPath: string): Promise<void> {
	const prettierConfigPath = path.join(rootPath, ".prettierrc.json");
	const prettierConfig = {
		useTabs: true,
		tabWidth: 4,
	};

	await writeFile(prettierConfigPath, JSON.stringify(prettierConfig));
}

async function setupESLintForPrettier(rootPath: string): Promise<void> {
    const eslintConfigPath = path.join(rootPath, ".eslintrc.json");
    const eslintConfig = {
		extends: ["prettier"],
	};

    await writeFile(eslintConfigPath, JSON.stringify(eslintConfig));
}

async function addFormatScriptToPackageJson(rootPath: string): Promise<void> {
    const packageJsonPath = path.join(rootPath, "package.json");

    const packageStr = await readFile(packageJsonPath, "utf-8");
    const packageJson = JSON.parse(packageStr);

    packageJson.scripts ??= {};

    packageJson.scripts.format = "prettier . --write";

    await writeFile(packageJsonPath, JSON.stringify(packageJson) + "\n");
}

async function addTypeModuleToPackageJson(rootPath: string): Promise<void> {
    const packageJsonPath = path.join(rootPath, "package.json");

    const packageStr = await readFile(packageJsonPath, "utf-8");
    const packageJson = JSON.parse(packageStr);

    packageJson.type = "module";

    await writeFile(packageJsonPath, JSON.stringify(packageJson) + "\n");
}

async function editLayoutMetadata(rootPath: string, title: string, desc: string): Promise<void> {
    const layoutPath = path.join(rootPath, "app", "layout.tsx");
    const layoutStr = await readFile(layoutPath, "utf-8");

    const updatedTitle = layoutStr.replace(/create next app/i, title);
    const updatedDesc = updatedTitle.replace(/generated by create next app/i, desc);

    await writeFile(layoutPath, updatedDesc);
}

async function initializeGitRepoAndCommit(rootPath: string): Promise<void> {
    await execa("git", ["init"], {
        cwd: rootPath,
        stdio: "inherit",
    });

    await execa("git", ["add", "."], {
        cwd: rootPath,
        stdio: "inherit",
    });

    await execa("git", ["commit", "-m", "Initial commit"], {
        cwd: rootPath,
        stdio: "inherit",
    });
}

async function setTailwindAndRootPageDefaults(rootPath: string): Promise<void> {
    const pagePath = path.join(rootPath, "app", "page.tsx");
    await writeFile(pagePath, 
        `export default function Home() { return <></>; }`
    );

    const cssPath = path.join(rootPath, "app", "globals.css");
    await writeFile(cssPath, 
        `@import "tailwindcss"`
    );
}
